global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'extractor'
    static_configs:
      - targets: ['extractor:8000']

  - job_name: 'transformer'
    static_configs:
      - targets: ['transformer:8001']

  - job_name: 'loader'
    static_configs:
      - targets: ['loader:8002']

  - job_name: 'api'
    static_configs:
      - targets: ['api:8003']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']